In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\surfce\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\surfce\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\surfce\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\surfce\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\surfce\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\surfce\anaconda3\Lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install matplotlib scikit-learn

Requirement already satisfied: matplotlib in C:\Users\surfce\anaconda3\Lib\site-packages (3.11.0)
Requirement already satisfied: scikit-learn in C:\Users\surfce\anaconda3\Lib\site-packages (1.9.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\surfce\anaconda3\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in C:\Users\surfce\anaconda3\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install seaborn

Requirement already satisfied: seaborn in C:\Users\surfce\anaconda3\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\surfce\anaconda3\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\surfce\anaconda3\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\surfce\anaconda3\Lib\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\surfce\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\surfce\anaconda3\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\surfce\anaconda3\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [6]:
data=pd.read_csv(r"C:\Users\surfce\Downloads\trends.csv")

In [7]:
data.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [8]:
data.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [9]:
data.info

<bound method DataFrame.info of       location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]>

In [10]:
data.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [11]:
data.shape

(26955, 5)

In [12]:
data.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='str')

In [13]:
data.dtypes

location      str
year        int64
category      str
rank        int64
query         str
dtype: object

In [14]:
data.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [15]:
int(data.duplicated().sum())

10

In [16]:
data.drop_duplicates(inplace=True)

In [17]:
data.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [18]:
column_name='rank'

In [19]:
Q1=data['rank'].quantile(0.25)

In [20]:
Q3=data['rank'].quantile(0.75)

In [21]:
IQR=Q3-Q1

In [22]:
print(Q1)

2.0

In [23]:
print(Q3)

4.0

In [24]:
print(IQR)

2.0

In [25]:
LF=Q1-1.5*IQR

In [26]:
UF=Q3+1.5*IQR

In [27]:
print(LF)

-1.0

In [28]:
print(UF)

7.0

In [29]:
outliers=data[(data['rank']<LF) | (data['rank']>UF)]

In [30]:
print(f"Number of outliers: {len(outliers)}")

Number of outliers: 0

In [31]:
display(outliers)

Empty DataFrame
Columns: [location, year, category, rank, query]
Index: []

In [32]:
column_name1='year'

In [33]:
Q1=data['year'].quantile(0.25)

In [35]:
Q3=data['year'].quantile(0.75)

In [36]:
IQR=Q3-Q1

In [37]:
print(Q1)
print(Q3)
print(IQR)

2013.0
2018.0
5.0

In [38]:
LF=Q1-1.5*IQR

In [39]:
UF=Q3+1.5*IQR

In [40]:
print(LF)

2005.5

In [41]:
print(UF)

2025.5

In [42]:
outliers=data[(data['year']<LF) | (data['year']>UF)]

In [43]:
print(f"Number of outliers: {len(outliers)}")

Number of outliers: 480

In [44]:
display(outliers)

    location  year         category  rank              query
0     Global  2001  Consumer Brands     1              Nokia
1     Global  2001  Consumer Brands     2               Sony
2     Global  2001  Consumer Brands     3                BMW
3     Global  2001  Consumer Brands     4               Palm
4     Global  2001  Consumer Brands     5              Adobe
..       ...   ...              ...   ...                ...
475   Global  2005    Most Searched     1      Janet Jackson
476   Global  2005    Most Searched     2  Hurricane Katrina
477   Global  2005    Most Searched     3            Tsunami
478   Global  2005    Most Searched     4           Xbox 360
479   Global  2005    Most Searched     5          Brad Pitt

[480 rows x 5 columns]